- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/usr/share/nginx/html/"
    remote_src: yes

- name: Set ownership
  file:
    path: "/usr/share/nginx/html/"
    state: directory
    recurse: yes
    owner: nginx
    group: nginx


- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory
    recurse: yes
    mode: '777'

- name: Copy sample config file
  command: mv /usr/share/nginx/html/wordpress/wp-config-sample.php /usr/share/nginx/html/wordpress/wp-config.php creates=/usr/share/nginx/html/wordpress/wp-config.php
  become: yes

- name: Update WordPress config file
  lineinfile:
    path: "/usr/share/nginx/html/wordpress/wp-config.php"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', 'wpdb' );"}
    - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', 'wpuser' );"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', 'password' );"}
  
